### ISSUE TITLE
Plugin not removing .js file

### ISSUE THREAD

**Issue by nealoke** [AnujRNair/webpack-extraneous-file-cleanup-plugin#1]
Hi :)

First of all is this problem still present with webpack 2? If so, this plugin is not removing my `js` file which is created from a `.scss` entry point. :)

**Comment by AnujRNair** [comment]
Hi @nealoke - I am using webpack2 and was still seeing this issue.
Can you provide your webpack config file for me so I can see the setup?
Thanks!

**Comment by nealoke** [comment]
Thanks for getting back to me :) See my current [production webpack file](https://gist.github.com/nealoke/a62cb967338128e5906d52a606aef170). It does not remove any file. Is it not possible to have the plugin work in a way where you specify the entry point of which the `.js` is created?

**Example**
```
new ExtraneousFileCleanupPlugin({
    entryPoint: ['styles']
    extensions: ['.js']
})
```

**Comment by AnujRNair** [comment]
Hi @nealoke - does the file you want removing have any contents in it? If so, would you be able to paste the contents here?

The plugin is designed to remove files which don't meet a certain byte size threshold, the default being 1024 bytes. If the file size is bigger than this, it won't be removed.

If the file _is_ below this byte size, would you be able to post a small reproducible example for me? Your webpack config file looks good to me, and without a reproducible example, I can't easily help you debug the issue you're facing.

Thanks!

**Comment by nealoke** [comment]
@AnujRNair what are your thoughts on my suggestion? :)

[Here is my output](https://gist.github.com/nealoke/81105553266dbd704f3a625f49366eba) file (which should be deleted), it is 29kb

**Comment by AnujRNair** [comment]
Hi @nealoke - it looks like your output chunk does have contents in it, which is causing the file size to increase over your defined threshold.

This plugin is designed to remove files which fall under a certain file size threshold, not necessarily know exactly which files to remove based on entry points etc.

Unfortunately, I don't think this plugin will solve the problem you are facing - you may have to search for another plugin to try and achieve exactly what you would like to.

Thanks!

**Comment by nealoke** [comment]
I found another plugin which simply ignores the assets you want it to, called [html-webpack-exclude-assets-plugin](https://github.com/jamesjieye/html-webpack-exclude-assets-plugin) which does the job perfectly :)
