### ISSUE TITLE
Error in remove .map 

### ISSUE THREAD

**Issue by Vladimirtishenko** [AnujRNair/webpack-extraneous-file-cleanup-plugin#2]
Please use wrap (try catch) for:

```
      fs.unlinkSync(outputPath + '/' + assetKey)          // unlink the asset
      fs.unlinkSync(outputPath + '/' + assetKey + '.map') // unlink the map file
      delete compilation.assets[assetKey]                 // remove from webpack output
      delete compilation.assets[assetKey + '.map']        // remove from webpack output
```

Because when I build it I get an error that says that it is not possible to delete the file .map and I do not have it.

**Comment by AnujRNair** [comment]
Hi @Vladimirtishenko - can you see if this PR solves what you're experiencing?
https://github.com/AnujRNair/webpack-extraneous-file-cleanup-plugin/pull/3

Thanks!

**Comment by AnujRNair** [comment]
Fixed with PR: https://github.com/AnujRNair/webpack-extraneous-file-cleanup-plugin/pull/3
