### ISSUE TITLE
Yarn cannot find on NPM registry

### ISSUE THREAD

**Issue by jordansykes** [AnujRNair/webpack-extraneous-file-cleanup-plugin#4]
When trying to install using yarn, I am getting the following error output:

error Couldn't find package "webpack-extraneous-file-cleanup-plugin" on the "npm" registry.

If I try the same thing using npm install, it seems to work?

**Comment by AnujRNair** [comment]
Hi @jordansykes - would you be able to give me a few more details about this issue?
* What environment are you on?
* Are you seeing the same issue if you run `yarn add webpack-extraneous-file-cleanup-plugin` in a fresh folder?
* Could you try upgrading yarn if it is not already up to date? `brew upgrade yarn`
* Could you show your current `package.json` file?

Thanks!

(I seem to be able to install in a fresh folder, so would love to understand more about your environment to help you solve this issue :) )

```
anujnair@Anuj-Mac-Pro tmp $ mkdir test
anujnair@Anuj-Mac-Pro tmp $ cd test/
anujnair@Anuj-Mac-Pro test $ yarn init
yarn init v0.27.5
question name (test):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
success Saved package.json
Done in 2.85s.
anujnair@Anuj-Mac-Pro test $ yarn add webpack-extraneous-file-cleanup-plugin
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ webpack-extraneous-file-cleanup-plugin@1.0.3
Done in 0.23s.
anujnair@Anuj-Mac-Pro test $ ls -la
total 16
drwxr-xr-x   5 anujnair  staff  170 Jul 27 09:46 .
drwxr-xr-x  17 anujnair  staff  578 Jul 27 09:45 ..
drwxr-xr-x   4 anujnair  staff  136 Jul 27 09:46 node_modules
-rw-r--r--   1 anujnair  staff  165 Jul 27 09:46 package.json
-rw-r--r--   1 anujnair  staff  324 Jul 27 09:46 yarn.lock
anujnair@Anuj-Mac-Pro test $ ls -la node_modules/
total 8
drwxr-xr-x  4 anujnair  staff  136 Jul 27 09:46 .
drwxr-xr-x  5 anujnair  staff  170 Jul 27 09:46 ..
-rw-r--r--  1 anujnair  staff  397 Jul 27 09:46 .yarn-integrity
drwxr-xr-x  9 anujnair  staff  306 Jul 27 09:46 webpack-extraneous-file-cleanup-plugin
```

**Comment by jordansykes** [comment]
Hi @AnujRNair It seems to be something in my configuration as when I yarn upgrade, it cannot find a lot of packages on the NPM registry, so sorry to waste your time, I will close the issue!
